[package]
name = "hex2dec"
version = "0.3.0"
edition = "2024"

[dependencies.clap]
version = "4.5.58"
features = ["derive"]

[dependencies.log]
version = "0.4.29"

[dependencies.env_logger]
version = "0.10"

[profile.release]
opt-level = 's'
codegen-units = 4
lto = "fat"
panic = "abort"