[package]
name = "hex2dec"
version = "0.1.0"
edition = "2024"

[dependencies.clap]
version = "4.5.57"
# default-features = false
features = ["derive"]

[dependencies.log]
version = "0.4"

[dependencies.env_logger]
version = "0.10"